[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts", 
"@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
"@uniswap/v3-core/contracts=lib/v3-core/contracts/",
"@uniswap/v3-periphery/contracts=lib/v3-periphery/contracts"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
